apiVersion: v1
kind: Pod
metadata:
  name: result
  labels:
    name: voting-app-pod
    app: result
spec:
  containers:
    - name: result
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
          name: result

